Tienda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('apiapp.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]


urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)



admin.site.site_title="Tienda Flowey"
admin.site.site_header="Administración de la tienda"
admin.site.index_title="Módulos de la tienda"

app/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', index, name="indexPrin"),
    path('index/', indexU, name="index"),
    path('carrito/', carritoCompras, name="carritoCompras"),
    path('historial/', historial, name="historial"),
    path('historial_detallado/<num_hist>', historial_detallado, name="historial_detallado"),
    path('registro/', registro, name="registro"),
    path('seguimiento/', seguimiento, name="seguimiento"),
    path('seguimientoAdmin/', seguimientoAdmin, name="seguimientoAdmin"),
    path('suscripcion/', suscripcion, name="suscripcion"),
    path('usuario/', usuario, name="usuario"),
    path('compra_exitosa/', compra_exitosa, name="compra_exitosa"),
    path('productos/', ventas, name="ventas"),
    path('base/', base, name="base"),
    path('ventas/', ventasDos, name="ventasDos"),
    path('ventas_api/', ventas_api, name="ventas_api"),
    path('api_smash/', api_smash, name="api_smash"),
    path('indexPrueba/', indexPrueba, name="indexPrueba"),
    path('onprocess/', onprocess, name="onprocess"),
    path('agregar/', agregar_producto, name="agregar_producto"),
    path('base2/', base2, name="base2"),
    path('listar_prod/', listar_productos, name="listar_productos"),
    path('listar_user/', listar_usuarios, name="listar_usuarios"),
    path('modificar_prod/<codigo>', modificar_producto, name="modificar_producto"),
    path('modificar_user/<id>', modificar_usuarios, name="modificar_usuarios"),
    path('modificar_seguimiento/<cod_seguimiento>', modificar_seguimiento, name="modificar_seguimiento"),
    path('eliminar_prod/<codigo>', eliminar_producto, name="eliminar_producto"),
    path('eliminar_user/<id>', eliminar_usuarios, name="eliminar_usuarios"),
    path('perfil/', perfil, name="perfil"),
    path('registro_usuarios/', registro_usuarios, name="registro_usuarios"),

    
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

app/models.py
from xml.dom.minidom import CharacterData
from django.db import models
#from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser



# Create your models here.
#Crear tablas sin declarar

class TipoProducto(models.Model):
    tipo = models.CharField(max_length=20)
    
    def __str__(self):
        return self.tipo
    
    class Meta:
        db_table='db_tipo_producto'

class Producto(models.Model):
    codigo = models.IntegerField(null=False, primary_key=True)
    nombre = models.CharField(max_length=20)
    marca = models.CharField(max_length=20)
    precio = models.IntegerField()
    descripcion = models.CharField(max_length=100)
    stock = models.IntegerField()
    tipo = models.ForeignKey(TipoProducto, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="productos", null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.nombre

    class Meta:
        db_table='db_producto'

class TipoCliente(models.Model):
    tipo = models.CharField(max_length=20)
    
    def __str__(self):
        return self.tipo

    class Meta:
        db_table='db_tipo_cliente'

class Cliente(models.Model):
    run = models.CharField(max_length=13,null=False, primary_key=True)
    nombre = models.CharField(max_length=20)
    apellido = models.CharField(max_length=20)
    clave = models.CharField(max_length=20)
    correo = models.CharField(max_length=25)
    region = models.CharField(max_length=25)
    comuna = models.CharField(max_length=25)
    direccion = models.CharField(max_length=150)
    tipo = models.ForeignKey(TipoCliente, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="usuarios", null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)


    def __str__(self):
        return self.nombre

    class Meta:
        db_table='db_cliente'


class TipoUser(models.Model):
    tipo = models.CharField(null=True, max_length=20)

    def __str__(self):
        return self.tipo
    
    class Meta:
        db_table='db_tipo_user'


class MainUser(AbstractUser):

    tipo = models.ForeignKey(TipoUser, on_delete=models.CASCADE, null=True)
    
    def __str__(self):
        return self.username


class Carrito (models.Model):
    cod_carr = models.AutoField(null=False, primary_key=True)
    comprado = models.BooleanField()
    total = models.IntegerField(null=True)
    descuento = models.IntegerField(null=True)
    subtotal = models.IntegerField(null=True)
    user = models.ForeignKey(MainUser, on_delete=models.CASCADE)

    def __int__(self):
        return self.cod_carr

    class Meta:
        db_table='db_carrito'


class Seguimiento(models.Model):
    cod_seguimiento = models.AutoField(primary_key=True, null=False)
    estado = models.CharField(max_length=20)
    user = models.ForeignKey(MainUser, on_delete=models.CASCADE)
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __int__(self):
        return self.cod_seguimiento

    class Meta:
        db_table='db_seguimiento'



class ElementCarrito(models.Model):

    cod_element_carrito = models.AutoField(null=False, primary_key=True)
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE)
    user = models.ForeignKey(MainUser, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    comprado = models.BooleanField()

    def __int__(self):
        return self.cod_element_carrito

    class Meta:
        db_table='db_element_carrito'




class TipoPago(models.Model):
    tipo = models.CharField(max_length=20)

    def __str__(self):
        return self.tipo

    class Meta:
        db_table='db_tipo_pago'



class Suscripcion(models.Model):
    user = models.ForeignKey(MainUser, on_delete=models.CASCADE)
    suscrito = models.BooleanField()

    def __boolean__(self):
        return self.suscrito

    class Meta:
        db_table='db_suscripcion'

class Historial(models.Model):
    num_hist = models.AutoField(primary_key=True, null = False)
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE)
    user = models.ForeignKey(MainUser, on_delete=models.CASCADE)
    seguimiento = models.ForeignKey(Seguimiento, on_delete=models.CASCADE)

    def __int__(self):
        return self.num_carrito

    class Meta:
        db_table='db_historial'



#class Historial (models.Model):

app/templates/app/productos/agregar_producto.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %} Agregar Productos {% endblock title %}
{% load crispy_forms_tags %}
{% block contenido %}

<section class="py-4 osahan-main-body">

    <div class="container">
        <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-lg-8">
                <form action="" method="POST" enctype="multipart/form-data">

                    {% csrf_token %}
                    <table>
                        {{ form|crispy }}
                    </table>    
                    <div style="display: flex; align-items: center; justify-content: center;">
                        <input type="submit" class="btn btn-success" value="Guardar" >
                    </div> 
                    
                </form>
                <div style="display: flex; text-align:center; font-family: 'Shadows Into Light'; justify-content: center; margin-top: 3%;">
                    <div > {% if messages %}
                                        {% for msj in messages %}
                                                <script>
                                                    Swal.fire({
                                                        title: 'Guardado!',
                                                        text: '{{ msj }}',
                                                        icon: 'success',
                                                        showConfirmButton: false,
                                                        timer: 2000
                                                    });
                                                </script>
                                            {% endfor %}
                                        {% endif %}</div>
                    
                </div>
            </div>
            <div class="col-sm-2"></div>
        </div>
    </div>

</section>
{% endblock %}

app/templates/app/productos/listar_productos.html
<!--se agrega en el form enctype="multipart/form-data"-->
{%extends 'app/base.html' %}

{% load static %}
{% block title %} Listar Productos {% endblock title %}
{%block contenido%}
<section>

<div>
    <div class="row">
        <div class="col-sm-12">
            <div>
                <table class="table table-bordered" style="width: 100%">
                    <thead>
                        <tr>
                            <th>CODIGO</th>
                            <th>NOMBRE</th>
                            <th>MARCA</th>
                            <th>PRECIO</th>
                            <th>DESCRIPCION</th>
                            <th>STOCK</th>
                            <th>TIPO</th>
                            <th>IMAGEN</th>
                            <th>FECHA CREACION</th>
                            <th>FECHA MODIFICACION</th>
                            <th>OPCIONES</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for aux in listarProductos %}
                        <tr>
                            <td>{{ aux.codigo }}</td>
                            <input type="hidden" name="codigo" id="codigo" value="{{ aux.codigo }}">
                            <td>{{ aux.nombre }}</td>
                            <td>{{ aux.marca }}</td>
                            <td>{{ aux.precio }}</td>
                            <td>{{ aux.descripcion }}</td>
                            <td>{{ aux.stock }}</td>
                            <td>{{ aux.tipo }}</td>
                            <td><img src="{{ aux.imagen.url }}" alt="" style="width: 80px;"></td>
                            <td>{{ aux.created_at }}</td>
                            <td>{{ aux.updated_at }}</td>
                            
                            <td>    
                                <div class="" style="text-align: center;">
                                    <a href="{% url 'modificar_producto' aux.codigo %}" class="btn btn-warning suavizado" style="width: 40px !important; margin-bottom: 5px; border-radius: 50% !important;"><i class="fa-solid fa-file-pen"></i></a>
                                    {% if perms.app.add_producto %}
                                    <a style="border-radius: 50% !important;" class="btn btn-danger suavizado" onclick="confirmacionProd('{{ aux.codigo }}')"><i class="fa-solid fa-trash-can"></i></a>
		                            {% endif %}
                                    
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>


            </div>
            
        </div>
    </div>
</div>

</section>
{% endblock%}

app/templates/app/productos/modificar_producto.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %} Modificar Productos {% endblock title %}
{% load crispy_forms_tags %}
{% block contenido %}

<section class="py-4 osahan-main-body">

    <div class="container">
        <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-lg-8">
                <form action="" method="POST" enctype="multipart/form-data">

                    {% csrf_token %}
                    <table>
                        {{ form|crispy }}
                    </table>    
                    <div style="display: flex; align-items: center; justify-content: center;">
                        <input type="submit" class="btn btn-success" value="Guardar" >
                    </div> 
                    
                </form>
                <div style="display: flex; text-align:center; font-family: 'Shadows Into Light'; justify-content: center; margin-top: 3%;">
                    {{ mensaje }}
                </div>
            </div>
            <div class="col-sm-2"></div>
        </div>
    </div>

</section>
{% endblock %}